name: project4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  buttons_tabbar: ^1.3.13
  customizable_counter: ^1.0.4
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/splash/
    - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Regular.ttf


flutter_native_splash:
  color: "#F28482"
  image: assets/splash/logo.png
  android_12: