name: shopping
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  shimmer_animation: ^2.2.1
  animations: ^2.0.11
  curved_navigation_bar: ^1.0.6
  clay_containers: ^0.3.4
  flutter_image_slideshow: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
