name: project4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  flutter_signin_button: ^2.0.0
  google_fonts: ^6.2.1
  fluid_bottom_nav_bar: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/Logo/
