name: shopping_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  google_fonts: ^6.2.1
  fluentui_system_icons: ^1.1.254
  shimmer_animation: ^2.2.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/
      
