name: shopping_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  quickalert: ^1.1.0  
  timelines: ^0.1.0
  flutter_rating_bar: ^4.0.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/laptops_images/
    - assets/general/
