name: espresso_yourself
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  page_view_dot_indicator: ^2.3.0
  badges: ^3.1.2
  avatar_glow: ^3.0.1
  qr_flutter: ^4.1.0
  animated_notch_bottom_bar: ^1.0.3
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/items/

  fonts:
    - family: Pliego
      fonts:
        - asset: fonts/Pliego-Regular.otf
          weight: 400
        - asset: fonts/Pliego-medium.otf
          weight: 500
        - asset: fonts/Pliego-semi-bold.otf
          weight: 600
        - asset: fonts/Pliego-bold.otf
          weight: 700